# Generated by Django 3.2.23 on 2024-02-12 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_restaurant_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='restuarant',
            new_name='restaurant',
        ),
    ]
